// src/app/layout.tsx
import type { Metadata } from 'next';

import { GlobalBusyOverlay } from '@/components/GlobalBusyOverlay';

import { Providers } from './providers';

import './globals.css';

export const metadata: Metadata = {
  title: 'chat-app',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <Providers>
          {children}
          <GlobalBusyOverlay />
        </Providers>
        <div id="portal-root"></div>
      </body>
    </html>
  );
}
